# build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci || npm i
COPY . .
RUN npm run build

# serve with nginx
FROM nginx:1.27-alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist ./
RUN printf "ok" > /usr/share/nginx/html/health
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
